#!/bin/sh

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@airconnect[-1]
	add ucitrack airconnect
	set ucitrack.@airconnect[-1].init=airconnect
	commit ucitrack
EOF
rm -rf /etc/init.d/cgroupfs-mount
rm -rf /tmp/luci-indexcache*
exit 0
